package net.bugabinga.annotation.bean.template;

/**
 * This class represents a JavaFX-{@link javafx.beans.property.Property} for the StringTemplate
 * template "auto_property_instance". It is our model, with which we fill the template.
 *
 * Created by bugabinga on 26.07.14.
 */
class Property {
/**
 * The abstract type of the property.
 */
  public final String type;
  /**
   * The long variable name of the property, conforming to property naming conventions.
   */
  public final String name;
  /**
   * More concrete implementation type of the property, relative to {@link Property#type}.
   */
  public final String impl;
  /**
   * Short variable name of the property according to naming conventions.
   */
  public final String simpleName;
  /**
   * The type of the property value.
   */
  public final String valueType;
  /**
   * Comment for the property access method.
   */
  public final String commentText;
  /**
   * Comment for the value setter method of the property.
   */
  public final String commentParam;
  /**
   * Comment for the value getter method of the property.
   */
  public final String commentReturn;

  //TODO(bugabinga): This class should really be generated by auto-value :)
  public Property(String type, String name, String impl, String simpleName, String simpleType,
                  String commentText,
                  String commentParam, String commentReturn) {
    this.type = type;
    this.name = name;
    this.impl = impl;
    this.simpleName = simpleName;
    this.valueType = simpleType;
    this.commentText = commentText;
    this.commentParam = commentParam;
    this.commentReturn = commentReturn;
  }
}
